# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\x19\n\x05\x45ntry\x12\x10\n\x08\x63ommands\x18\x01 \x03(\t\"\xaa\x01\n\x12\x41ppendEntryRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1c\n\x07\x65ntries\x18\x05 \x01(\x0b\x32\x0b.raft.Entry\x12\x15\n\rleaseDuration\x18\x06 \x01(\x02\x12\x14\n\x0cleaderCommit\x18\x07 \x01(\x05\"Q\n\x13\x41ppendEntryResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06nodeId\x18\x03 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x04 \x01(\x05\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"_\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x12\x0e\n\x06nodeId\x18\x03 \x01(\x05\x12\x15\n\rleaseDuration\x18\x04 \x01(\x02\"\"\n\x0fServeClientArgs\x12\x0f\n\x07Request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\t\x12\x0f\n\x07Success\x18\x03 \x01(\x08\x32\xda\x01\n\x0craft_service\x12\x44\n\x0b\x61ppendEntry\x12\x18.raft.AppendEntryRequest\x1a\x19.raft.AppendEntryResponse\"\x00\x12\x44\n\x0brequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\"\x00\x12>\n\x0bserveClient\x12\x15.raft.ServeClientArgs\x1a\x16.raft.ServeClientReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTRY']._serialized_start=20
  _globals['_ENTRY']._serialized_end=45
  _globals['_APPENDENTRYREQUEST']._serialized_start=48
  _globals['_APPENDENTRYREQUEST']._serialized_end=218
  _globals['_APPENDENTRYRESPONSE']._serialized_start=220
  _globals['_APPENDENTRYRESPONSE']._serialized_end=301
  _globals['_REQUESTVOTEREQUEST']._serialized_start=303
  _globals['_REQUESTVOTEREQUEST']._serialized_end=401
  _globals['_REQUESTVOTERESPONSE']._serialized_start=403
  _globals['_REQUESTVOTERESPONSE']._serialized_end=498
  _globals['_SERVECLIENTARGS']._serialized_start=500
  _globals['_SERVECLIENTARGS']._serialized_end=534
  _globals['_SERVECLIENTREPLY']._serialized_start=536
  _globals['_SERVECLIENTREPLY']._serialized_end=603
  _globals['_RAFT_SERVICE']._serialized_start=606
  _globals['_RAFT_SERVICE']._serialized_end=824
# @@protoc_insertion_point(module_scope)
